'use strict';
/* STMX TC INTEGRATED RUNTIME V1 — interface contract tests (V2.3.91 §27 · §28 · §29 · §30). Synthetic governed packages only:
 * no corpus identity, no GT, no image, no historical Strength label. Exports `results`; prints a summary when run directly. */
const path = require('path');
const RT = require(path.join(__dirname, '..', 'src', 'tc_integrated_runtime_v1.js'));
const PROJ = require(path.join(__dirname, '..', '..', 'STMX_TC_ORDINAL_PROJECTOR_V1_CANDIDATE', 'src', 'tc_ordinal_projector_v1.js'));
const S = RT.INPUT_SCHEMA, A = RT.DIRECTION_AUTHORITY;
const pkg = (direction, extra) => Object.assign({ schema_version: S, direction_authority: A, direction }, extra || {});
const results = [];
const t = (id, name, fn) => { try { const r = fn(); results.push({ id, name, ok: r === true, detail: r === true ? 'ok' : String(r) }); } catch (e) { results.push({ id, name, ok: false, detail: 'threw ' + e.message }); } };
const refuses = (p, code) => { try { RT.integrateUnit(p); return 'accepted'; } catch (e) { return e.code === code ? true : 'code ' + e.code; } };
const strip = (o) => { const x = JSON.parse(JSON.stringify(o)); delete x.subject_ref; x.provenance = { projector: x.provenance.projector, contract: x.provenance.contract, rule: x.provenance.rule }; return JSON.stringify(x); };
const standalone = (direction) => { const s = RT.strengthStatus(direction); return PROJ.project({ direction, direction_status: RT.directionStatus(direction), strength: s.strength, strength_status: s.strength_status }); };

// §28 arbitrary new-input contract: synthetic identities, no corpus lookup
t('T01', 'synthetic CLASSIC package → null score · TC1–TC4 · CLASSIC_IDENTITY_LIMITATION', () => { const o = RT.integrateUnit(pkg('CLASSIC', { subject_ref: 'SYNTHETIC-0001' })); return o.score === null && o.score_status === 'UNRESOLVED' && o.ordinal_status === 'SIDE_KNOWN_WITHIN_SIDE_UNRESOLVED' && o.ordinal_bounds.min === 'TC1' && o.ordinal_bounds.max === 'TC4' && o.unresolved_cause === 'CLASSIC_IDENTITY_LIMITATION' && o.strength === 'NOT_APPLICABLE' || JSON.stringify(o); });
t('T02', 'synthetic TRANSFORMATIVE package (no Strength supplied) → Strength UNRESOLVED · KNOWN_INFORMATION_OR_REPRESENTATION_LIMITATION · TC6–TC9', () => { const o = RT.integrateUnit(pkg('TRANSFORMATIVE', { subject_ref: 'X-new-garment' })); return o.score === null && o.strength === 'UNRESOLVED' && o.strength_status === 'KNOWN_INFORMATION_OR_REPRESENTATION_LIMITATION' && o.ordinal_bounds.min === 'TC6' && o.ordinal_bounds.max === 'TC9' && o.unresolved_cause === 'TRANSFORMATIVE_STRENGTH_AUTOMATION_LIMITATION' || JSON.stringify(o); });
t('T03', 'synthetic DIRECTION_UNRESOLVED package → NOT_ELIGIBLE · no bounds · Strength NOT_ELIGIBLE', () => { const o = RT.integrateUnit(pkg('DIRECTION_UNRESOLVED')); return o.score === null && o.ordinal_status === 'NOT_ELIGIBLE' && o.ordinal_bounds === null && o.strength === 'NOT_ELIGIBLE' && o.unresolved_cause === 'DIRECTION_UNRESOLVED' || JSON.stringify(o); });
t('T04', 'integrated output = standalone projector output for every Direction (projector-owned fields)', () => ['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED'].every((d) => strip(RT.integrateUnit(pkg(d, { subject_ref: 'q' }))) === strip(standalone(d))) || 'mismatch');
t('T05', 'Direction passes through verbatim (no C↔T, no U→C/T)', () => ['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED'].every((d) => RT.integrateUnit(pkg(d)).direction === d) || 'changed');
// §27 identity: synthetic IDs and processing order do not change semantics
t('T06', 'identity-free: 60 synthetic IDs, three orders → identical semantics per Direction', () => { const dirs = ['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED']; const ids = Array.from({ length: 60 }, (_, i) => ({ id: 'SYN-' + ((i * 7919) % 1000), d: dirs[i % 3] }));
  const run = (arr) => new Map(arr.map((x) => [x.id + '|' + x.d, strip(RT.integrateUnit(pkg(x.d, { subject_ref: x.id })))]));
  const a = run(ids), b = run([...ids].reverse()), c = run([...ids].sort((p, q) => (p.id < q.id ? 1 : -1)));
  const per = new Set(ids.map((x) => x.d + '|' + a.get(x.id + '|' + x.d))); return [...a.keys()].every((k) => a.get(k) === b.get(k) && a.get(k) === c.get(k)) && per.size === 3 || 'identity-dependent'; });
t('T07', 'subject_ref is echoed only; changing it changes nothing else', () => strip(RT.integrateUnit(pkg('TRANSFORMATIVE', { subject_ref: 'A' }))) === strip(RT.integrateUnit(pkg('TRANSFORMATIVE', { subject_ref: 'ZZZ-999' }))) || 'differs');
// §29 malformed / missing input
t('T08', 'missing Direction → DIRECTION_MISSING', () => refuses({ schema_version: S, direction_authority: A }, 'DIRECTION_MISSING'));
t('T09', 'invalid Direction enum (C4 · classic · T6 · padded) → DIRECTION_INVALID', () => ['C4', 'classic', 'T6', 'TRANSFORMATIVE '].every((d) => refuses(pkg(d), 'DIRECTION_INVALID') === true) || 'accepted an invalid Direction');
t('T10', 'Classic with an accidental Transformative Strength field → STRENGTH_SOURCE_NOT_GOVERNED', () => refuses(pkg('CLASSIC', { strength: 'WEAK' }), 'STRENGTH_SOURCE_NOT_GOVERNED'));
t('T11', 'Transformative with an invalid Strength (MEDIUM) → STRENGTH_SOURCE_NOT_GOVERNED', () => refuses(pkg('TRANSFORMATIVE', { strength: 'MEDIUM' }), 'STRENGTH_SOURCE_NOT_GOVERNED'));
t('T12', 'Transformative with a W/R/S label (no governed source) → refused, never consumed', () => ['WEAK', 'REGULAR', 'STRONG'].every((s) => refuses(pkg('TRANSFORMATIVE', { strength: s }), 'STRENGTH_SOURCE_NOT_GOVERNED') === true && refuses(pkg('TRANSFORMATIVE', { strength_status: 'GOVERNED' }), 'STRENGTH_SOURCE_NOT_GOVERNED') === true) || 'a W/R/S entered');
t('T13', 'illegal exact score injected upstream (TC7 · 7 · tier) → SCORE_INJECTION_REFUSED', () => [{ score: 'TC7' }, { score: 7 }, { tier: 'TC6' }, { score_status: 'OK' }].every((x) => refuses(pkg('TRANSFORMATIVE', x), 'SCORE_INJECTION_REFUSED') === true) || 'score accepted');
t('T14', 'TC5 injected (score · bounds) → refused', () => refuses(pkg('CLASSIC', { score: 'TC5' }), 'SCORE_INJECTION_REFUSED') === true && refuses(pkg('CLASSIC', { ordinal_bounds: { side: 'CLASSIC', min: 'TC4', max: 'TC5' } }), 'ORDINAL_INJECTION_REFUSED') === true || 'TC5 accepted');
t('T15', 'malformed ordinal bounds injected → ORDINAL_INJECTION_REFUSED', () => [{ ordinal_bounds: { min: 'TC9', max: 'TC1' } }, { ordinal_bounds: 'TC1-TC4' }, { ordinal_status: 'EXACT' }].every((x) => refuses(pkg('CLASSIC', x), 'ORDINAL_INJECTION_REFUSED') === true) || 'bounds accepted');
t('T16', 'unknown / missing schema version → SCHEMA_VERSION_UNKNOWN', () => refuses(Object.assign(pkg('CLASSIC'), { schema_version: 'STMX_TC_INTEGRATED_INPUT_V9' }), 'SCHEMA_VERSION_UNKNOWN') === true && refuses({ direction_authority: A, direction: 'CLASSIC' }, 'SCHEMA_VERSION_UNKNOWN') === true || 'accepted');
t('T17', 'unknown Direction authority → DIRECTION_AUTHORITY_UNKNOWN', () => refuses(Object.assign(pkg('CLASSIC'), { direction_authority: 'STEP3_FROZEN_BASELINE_V1' }), 'DIRECTION_AUTHORITY_UNKNOWN'));
t('T18', 'non-object inputs → INPUT_NOT_OBJECT', () => [null, undefined, 'CLASSIC', ['CLASSIC'], 4].every((x) => refuses(x, 'INPUT_NOT_OBJECT') === true) || 'accepted');
t('T19', 'foreign fields (direction_status · grammar_state · magnitude · anchor_id · gt) → INPUT_FIELD_NOT_ALLOWED', () => ['direction_status', 'grammar_state', 'magnitude', 'anchor_id', 'gt', 'reference_key'].every((k) => refuses(pkg('CLASSIC', { [k]: 'x' }), 'INPUT_FIELD_NOT_ALLOWED') === true) || 'accepted');
t('T20', 'non-string subject_ref → SUBJECT_REF_INVALID', () => refuses(pkg('CLASSIC', { subject_ref: 17 }), 'SUBJECT_REF_INVALID'));
// strength router + output guard
t('T21', 'Strength router: C → NOT_APPLICABLE · T → UNRESOLVED (limitation) · U → NOT_ELIGIBLE; no resolver wired', () => RT.GOVERNED_STRENGTH_RESOLVER === null && RT.strengthStatus('CLASSIC').strength === 'NOT_APPLICABLE' && RT.strengthStatus('TRANSFORMATIVE').strength_status === 'KNOWN_INFORMATION_OR_REPRESENTATION_LIMITATION' && RT.strengthStatus('DIRECTION_UNRESOLVED').strength === 'NOT_ELIGIBLE' || 'router');
t('T22', 'Strength unavailable is never rewritten as not needed (T ≠ NOT_APPLICABLE)', () => RT.integrateUnit(pkg('TRANSFORMATIVE')).strength !== 'NOT_APPLICABLE' || 'rewritten');
t('T23', 'output guard refuses a forged exact score, TC5, a side crossing and a changed Direction', () => { const base = RT.integrateUnit(pkg('TRANSFORMATIVE')); const forge = (m) => { const o = JSON.parse(JSON.stringify(base)); m(o); try { RT.assertOutput(o, 'TRANSFORMATIVE'); return false; } catch (e) { return e.code === 'OUTPUT_CONTRACT_VIOLATION'; } };
  return forge((o) => { o.score = 'TC7'; o.score_status = 'OK'; }) && forge((o) => { o.ordinal_bounds.max = 'TC5'; }) && forge((o) => { o.ordinal_bounds = { side: 'CLASSIC', min: 'TC1', max: 'TC4' }; }) && forge((o) => { o.direction = 'CLASSIC'; }) || 'guard let a forgery through'; });
// §30 provenance
t('T24', 'provenance complete: Direction authority · Strength contract / limitation / resolver · ordinal contract · projector · rule · integrated runtime', () => ['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED'].every((d) => { const p = RT.integrateUnit(pkg(d)).provenance; return p.direction_authority === 'STMX_TC_DIRECTION_FREEZE_V1' && p.strength_authority.contract === 'STMX_TC_TRANSFORMATIVE_STRENGTH_SEMANTIC_CONTRACT_FREEZE_V1' && p.strength_authority.limitation_record === 'STMX_TC_TRANSFORMATIVE_STRENGTH_AUTOMATION_LIMITATION_RECORD_V1' && p.strength_authority.automatic_resolver === 'NONE' && p.contract === 'STMX_TC_ORDINAL_REPRESENTATION_CONTRACT_FREEZE_V1' && p.projector === 'STMX_TC_ORDINAL_PROJECTOR_V1_CANDIDATE' && /^O-5\//.test(p.rule) && p.integrated_runtime === 'STMX_TC_INTEGRATED_RUNTIME_V1_CANDIDATE'; }) || 'incomplete');
t('T25', 'no TC5 anywhere in any lawful output; no exact score in any lawful output', () => ['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED'].every((d) => { const o = RT.integrateUnit(pkg(d)); return !/TC5/.test(JSON.stringify(o)) && o.score === null; }) || 'TC5 or exact');
t('T26', 'deterministic: 200 repeated calls produce byte-identical output', () => { const s = new Set(); for (let i = 0; i < 200; i++) s.add(JSON.stringify(RT.integrateUnit(pkg(['CLASSIC', 'TRANSFORMATIVE', 'DIRECTION_UNRESOLVED'][i % 3], { subject_ref: 'D' })))); return s.size === 3 || 'non-deterministic'; });

module.exports = { results };
if (require.main === module) { const p = results.filter((r) => r.ok).length; for (const r of results) if (!r.ok) console.log('FAIL', r.id, r.name, r.detail); console.log(JSON.stringify({ pass: p, total: results.length })); if (p !== results.length) process.exitCode = 1; }
