'use strict';
/* VERIFICATION_TOOL — Step 2 successor V4 test runner (V2.3.86). Prints JSON; writes nothing.
 * (1) V4 fixtures (D-85-1 · sleeve anti-generalization) · (2) V3 fixture suite under V4 · (3) V2.3.80 09A suite under V4 · (4) SOR unit tests ·
 * (5) V4 without SHC / SOR ≡ V3 on every fixture · (6) source scans. */
const fs = require('fs'), path = require('path');
const PKG = path.resolve(__dirname, '..'); const ROOT = path.resolve(PKG, '..', '..', '..');
const V4 = require(path.join(PKG, 'src/step2_semantic_successor_v4.js')); const V3 = require(path.join(ROOT, '01_ENGINES/ITEM_SCORING_ENGINE/STMX_TC_STEP2_SEMANTIC_SUCCESSOR_V3_CANDIDATE/src/step2_semantic_successor_v3.js'));
const tok = (v) => { if (typeof v === 'string') return { state: 'OBSERVED', value: v, values: null }; if (v && v.byRegion) return { state: 'OBSERVED', value: v.value === undefined ? null : v.value, values: null, byRegion: v.byRegion }; if (v && Array.isArray(v.values_detail)) return { state: 'OBSERVED', value: null, values: v.values_detail.map((d) => d.value), values_detail: v.values_detail }; if (v && v.state) return { state: v.state, value: null, values: null }; return v; };
const toks = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, tok(v)]));
const S = V4.createSuccessor({ registry: 'EMPTY' }); const S3eq = V4.createSuccessor({ registry: 'EMPTY', rules: ['GRC', 'WG', 'MC1'] }); const S3 = V3.createSuccessor({ registry: 'EMPTY' });
const check = (r, e) => { const f = []; for (const [k, ch] of [['silhouette', 'silhouette'], ['proportion', 'proportion'], ['construction', 'construction']]) { if (e[k] && r[ch].v !== e[k]) f.push(k + ' ' + r[ch].v); if (e[k + '_rule'] && r[ch].rule !== e[k + '_rule']) f.push(k + '_rule ' + r[ch].rule); } if (e.direction && r.direction !== e.direction) f.push('direction ' + r.direction); return f; };
const F4 = JSON.parse(fs.readFileSync(path.join(__dirname, 'successor_v4_fixtures_v2386.json'), 'utf8'));
const r4 = F4.fixtures.map((x) => { const r = S.evaluateMember(toks(x.tokens), x.key, []); const f = check(r, x.expect); return { id: x.id, group: x.group, key: x.key, silhouette: r.silhouette.rule, direction: r.direction, rules: r.provenance.input_contract_rules, pass: !f.length, fail: f }; });
const F3 = JSON.parse(fs.readFileSync(path.join(ROOT, '01_ENGINES/ITEM_SCORING_ENGINE/STMX_TC_STEP2_SEMANTIC_SUCCESSOR_V3_CANDIDATE/tests/successor_v3_fixtures_v2384.json'), 'utf8'));
const r3 = F3.fixtures.map((x) => { const r = S.evaluateMember(toks(x.tokens), x.key, []); const f = check(r, x.expect); return { id: x.id, pass: !f.length, fail: f }; });
const A09 = JSON.parse(fs.readFileSync(path.join(ROOT, '04_GOVERNANCE_AND_FINAL_DOCS/STMX_TC_MAINLINE_V2_3_80_DIRECTION_FIRST_ENGINE_SUFFICIENCY_AND_SIMPLIFICATION_AUDIT/09A_CROPPED_OVERSIZED_REGRESSION_FIXTURES.json'), 'utf8'));
const obs = (kv) => { const o = {}; for (const [k, v] of Object.entries(kv)) { if (v && typeof v === 'object' && Array.isArray(v.values_detail)) o[k] = { state: 'OBSERVED', value: null, values: v.values_detail.map((d) => d.value), values_detail: v.values_detail }; else if (v && typeof v === 'object' && v.state) o[k] = v; else o[k] = { state: 'OBSERVED', value: v }; } return o; };
// expectations superseded by a later CEO decision (the sealed 09A file is never edited; the supersession is explicit and narrow)
const SUPERSEDED = { B1: { expect: 'CLASSIC', authority: 'CEO D-85-1 (V2.3.86): a Strong shoulder on JACKET:Tailored is conventional tailored structure — the "no FALSE rule exists" premise of B1 (AU-18) is closed by that decision' } };
const r09 = A09.fixtures.map((x) => { const r = S.evaluateMember(obs(x.observation), x.key, x.asy_evidence || []); const sup = SUPERSEDED[x.id]; const exp = sup ? sup.expect : x.expect_direction; const pass = /^NOT_TRANSFORMATIVE/.test(exp) ? r.direction !== 'TRANSFORMATIVE' : r.direction === exp; return { id: x.id, expect: exp, original_expect: sup ? x.expect_direction : undefined, superseded_by: sup ? sup.authority : undefined, v4: r.direction, pass }; });
// SOR unit tests (the only anchors the sealed record lists)
const rec = (ref, dir) => ({ garment_ref: ref, direction: dir, silhouette: { v: 'FALSE', rule: 'SIL-FALSE-LADDER' }, proportion: { v: 'FALSE', rule: 'PRO-FALSE-Q5' }, construction: { v: 'FALSE', rule: 'CON-FALSE-C1' }, asymmetry: { departure_exists: false } });
const unit = [
  { id: 'SOR-01', ok: S.materializeUnit(V4.SCORING_OBJECT_ANCHORS[0], 'GARMENT', [rec('target_1', 'CLASSIC'), rec('target_2', 'DIRECTION_UNRESOLVED'), rec('target_3', 'DIRECTION_UNRESOLVED')]).direction === 'CLASSIC', what: 'recorded member alone forms the unit; context garments excluded' },
  { id: 'SOR-02', ok: S.materializeUnitHistorical(V4.SCORING_OBJECT_ANCHORS[0], 'GARMENT', [rec('target_1', 'CLASSIC'), rec('target_2', 'DIRECTION_UNRESOLVED')]).direction === null, what: 'historical aggregation unchanged (no Direction for a multi-member GARMENT)' },
  { id: 'SOR-03', ok: S.materializeUnit('ANCHOR_NOT_IN_RECORD#SU1', 'GARMENT', [rec('target_1', 'CLASSIC'), rec('target_2', 'CLASSIC')]).direction === null, what: 'no record → no membership change (no look-level TC, no aggregation)' },
  { id: 'SOR-04', ok: (() => { try { S.materializeUnit(V4.SCORING_OBJECT_ANCHORS[0], 'GARMENT', [rec('target_2', 'CLASSIC')]); return false; } catch (e) { return e instanceof V4.ContractError; } })(), what: 'recorded member missing → fail closed' },
  { id: 'SOR-05', ok: (() => { const u = S.materializeUnit(V4.SCORING_OBJECT_ANCHORS[1], 'GARMENT', [Object.assign(rec('target_1', 'TRANSFORMATIVE'), { proportion: { v: 'TRUE', rule: 'PRO-TRUE-Q5' } }), Object.assign(rec('target_3', 'TRANSFORMATIVE'), { construction: { v: 'TRUE', rule: 'CON-TRUE-X' } })]); return u.direction === 'TRANSFORMATIVE' && u.statement_set.join() === 'PROPORTION:PRO-TRUE-Q5'; })(), what: 'context garment departures never enter the unit' }];
const eq = F4.fixtures.concat(F3.fixtures).map((x) => { const t = toks(x.tokens); const a = S3eq.evaluateMember(t, x.key, []), b = S3.evaluateMember(t, x.key, []); const st = (r) => JSON.stringify([r.silhouette, r.proportion, r.construction, r.asymmetry, r.direction]); return { id: x.id, equal: st(a) === st(b) }; });
const src = fs.readFileSync(path.join(PKG, 'src/step2_semantic_successor_v4.js'), 'utf8').split('\n').filter((l) => !/^const FORBIDDEN_OUT_KEYS = /.test(l)).join('\n'); const bind = fs.readFileSync(path.join(PKG, 'shadow/step2_successor_shadow_binding_v3.js'), 'utf8');
const scans = { ref_id_in_source: /REF_\d{6}/.test(src + bind), gt_field_in_source: /ceo_ground_truth|historical_tc|gt_side/.test(src + bind), regional_direction_symbol: /regional_direction|upperDirection|lowerDirection/.test(src + bind), sleeve_or_cuff_rule: /cuff_scale|cuff_type/.test(src + bind), strong_to_true_shortcut: /Strong['"]?\s*\)\s*\?\s*\{\s*v:\s*'TRUE'/.test(src) };
const out = { runner: 'run_successor_v4_tests_v2386', successor: V4.SUCCESSOR_ID, v4_fixtures: { total: r4.length, pass: r4.filter((r) => r.pass).length, results: r4 }, v3_fixtures_under_v4: { total: r3.length, pass: r3.filter((r) => r.pass).length, fail: r3.filter((r) => !r.pass) }, regression_09A: { total: r09.length, pass: r09.filter((r) => r.pass).length, fail: r09.filter((r) => !r.pass) }, sor_unit_tests: unit, equivalence_without_SHC_SOR_vs_v3: { total: eq.length, equal: eq.filter((e) => e.equal).length, diff: eq.filter((e) => !e.equal).map((e) => e.id) }, scans };
out.ok = out.v4_fixtures.pass === out.v4_fixtures.total && out.v3_fixtures_under_v4.pass === out.v3_fixtures_under_v4.total && out.regression_09A.pass === out.regression_09A.total && unit.every((u) => u.ok) && out.equivalence_without_SHC_SOR_vs_v3.equal === out.equivalence_without_SHC_SOR_vs_v3.total && !Object.values(scans).some(Boolean);
process.stdout.write(JSON.stringify(out, null, 1));
