'use strict';
/*
 * Shadow — L2 Canonical Equivalence Comparator (Sprint 3).
 * Legacy canonical view vs Clean L2 canonical (values + unknowns). deep_equal reused. No new status.
 * Status: MATCH | EXPECTED_DIFF (forbidden not generated by L2) | MISMATCH.
 */
const l1 = require('../../04_CLEAN_ENGINE_CODE/src/layers/l1_observation');
const l2 = require('../../04_CLEAN_ENGINE_CODE/src/layers/l2_canonical');
const { legacyCanonicalView } = require('../runners/legacy_canonical_adapter');
const { FORBIDDEN } = require('../../04_CLEAN_ENGINE_CODE/src/layers/l2_field_spec');
const { deepEqual } = require('../../04_CLEAN_ENGINE_CODE/src/runtime/deep_equal');

function flattenL2(canPkg) {
  var flat = {};
  var d = (canPkg && canPkg.data) || {};
  var can = d.canonical || {};
  Object.keys(can).forEach(function (obj) {
    Object.keys(can[obj]).forEach(function (f) { flat[obj + '.' + f] = can[obj][f].value; });
  });
  var unk = d.unknowns || {};
  Object.keys(unk).forEach(function (obj) {
    Object.keys(unk[obj]).forEach(function (f) { flat[obj + '.' + f] = unk[obj][f].value; });
  });
  return flat;
}

function compareMaps(legacy, clean, forbiddenGenerated) {
  forbiddenGenerated = forbiddenGenerated || [];
  // Scope declaration (§8): what this comparison covers, and explicitly what it does NOT.
  var result = {
    scope: 'FIELD_LEVEL_CANONICAL_REFERENCE',
    behavioral_oracle: false,   // Legacy engine NOT executed
    covers: ['canonical field presence', 'canonical value', 'unknown passthrough',
             'forbidden exclusion', 'field-level deterministic equality'],
    does_not_cover: ['Legacy engine behavioral outcome', 'Derived', 'Projection', 'Scoring',
                     'Cross-axis', 'Governance', 'Decision output'],
    MATCH: 0, EXPECTED_DIFF: 0, MISMATCH: 0, items: [], map: {},
  };
  Object.keys(legacy).forEach(function (key) {
    var status, extra = {};
    var shortField = key.indexOf('.') !== -1 ? key.split('.').pop() : key;
    if (FORBIDDEN.indexOf(shortField) !== -1) {
      status = (forbiddenGenerated.indexOf(key) === -1) ? 'EXPECTED_DIFF' : 'MISMATCH';
    } else if (Object.prototype.hasOwnProperty.call(clean, key) && deepEqual(clean[key], legacy[key])) {
      status = 'MATCH';
    } else {
      status = 'MISMATCH'; extra = { legacy: legacy[key], clean: clean[key] };
    }
    result[status]++; result.map[key] = status;
    result.items.push(Object.assign({ key: key, status: status }, extra));
  });
  result.equivalent = (result.MISMATCH === 0);
  return result;
}

function compareCanonical(vision, opts) {
  var obsPkg = l1(vision, opts || {});
  var canPkg = l2(obsPkg);
  var legacy = legacyCanonicalView(obsPkg);
  var clean = flattenL2(canPkg);
  var forbiddenGenerated = (canPkg.data.validation.forbidden_present) || [];
  return compareMaps(legacy, clean, forbiddenGenerated);
}

module.exports = { compareCanonical, compareMaps, flattenL2 };
